import type { Metadata } from "next";

export const siteConfig: Metadata = {
  title: "Daniel Pereira | Space Portfolio",
  description: "Bem-vindo ao meu portfólio de desenvolvimento e projetos em Java, Spring Boot e Front-end moderno.",
  keywords: [
    "reactjs",
    "nextjs",
    "vercel",
    "react",
    "space-portfolio",
    "portfolio",
    "react-icons",
    "cn",
    "clsx",
    "3d-portfolio",
    "3d-website",
    "sonner",
    "framer-motion",
    "motion",
    "animation",
    "heroicons",
    "next-themes",
    "postcss",
    "prettier",
    "react-dom",
    "tailwindcss",
    "tailwindcss-animate",
    "ui/ux",
    "js",
    "javascript",
    "typescript",
    "eslint",
    "html",
    "css",
  ] as Array<string>,
  authors: {
    name: "Sanidhya Kumar Verma, Daniel Pereira",
    url: "https://github.com/danielp6r/space-portfolio",
  },
} as const;
